#!/usr/bin/env python3
"""
md2blog — Turn a folder of Markdown files into a static blog in 1 second.

Drag a folder of .md files, run one command, get a complete blog site.
No config. No database. No JavaScript frameworks.

Author: Caishen AI (caishen-ai@qq.com)
License: MIT
"""

import os
import re
import shutil
import argparse
from datetime import datetime
from pathlib import Path

# ============================================================
# HTML TEMPLATES
# ============================================================

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="{description}">
<title>{title}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:system-ui,-apple-system,sans-serif;line-height:1.7;color:#333;background:#fafafa}}
.container{{max-width:800px;margin:0 auto;padding:20px 16px}}
.header{{text-align:center;padding:60px 0 30px;border-bottom:1px solid #e5e5e5;margin-bottom:40px}}
.header h1{{font-size:2em;color:#111}}
.header p{{color:#666;margin-top:10px}}
.post{{margin-bottom:50px}}
.post h2{{margin-bottom:8px}}
.post h2 a{{color:#222;text-decoration:none}}
.post h2 a:hover{{color:#0066cc}}
.meta{{color:#999;font-size:0.85em;margin-bottom:12px}}
.content{{font-size:1.05em;line-height:1.8}}
.content h1,.content h2,.content h3{{margin:24px 0 12px;color:#222}}
.content p{{margin-bottom:16px}}
.content code{{background:#f0f0f0;padding:2px 6px;border-radius:3px;font-size:0.9em}}
.content pre{{background:#1e1e1e;color:#d4d4d4;padding:16px;border-radius:6px;overflow-x:auto;margin-bottom:16px;font-size:0.85em;line-height:1.5}}
.content pre code{{background:none;padding:0}}
.content a{{color:#0066cc}}
.content img{{max-width:100%;border-radius:4px}}
.content blockquote{{border-left:3px solid #0066cc;padding-left:16px;margin:16px 0;color:#555}}
.content ul,.content ol{{margin:12px 0 12px 24px}}
.content li{{margin-bottom:4px}}
.footer{{text-align:center;padding:40px 16px;color:#999;font-size:0.85em;border-top:1px solid #e5e5e5;margin-top:60px}}
.cta{{background:#f0f7ff;border:1px solid #b3d9ff;border-radius:8px;padding:20px;margin:30px 0;text-align:center}}
.cta p{{margin-bottom:10px}}
.cta a.btn{{display:inline-block;background:#0066cc;color:#fff;padding:10px 24px;border-radius:5px;text-decoration:none;font-weight:600}}
.cta a.btn:hover{{background:#0052a3}}
.nav{{text-align:center;margin-bottom:30px}}
.nav a{{margin:0 12px;color:#0066cc;text-decoration:none}}
.nav a:hover{{text-decoration:underline}}
.table-wrapper{{overflow-x:auto;margin-bottom:16px}}
table{{border-collapse:collapse;width:100%}}
table th,table td{{border:1px solid #ddd;padding:8px 12px;text-align:left}}
table th{{background:#f5f5f5;font-weight:600}}
</style>
</head>
<body>
<div class="container">
{header}
<main>
{body}
</main>
</div>
<div class="footer">
  <p>Generated by <a href="https://github.com/caishen-ai/md2blog">md2blog</a> — The 1-second static blog generator</p>
  <p>Need customisation? <a href="mailto:caishen-ai@qq.com">caishen-ai@qq.com</a></p>
</div>
</body>
</html>"""

INDEX_HEADER = """<div class="header">
<h1>{blog_title}</h1>
<p>{blog_description}</p>
</div>"""

POST_HEADER = """<div class="nav">
<a href="/">← Home</a>
</div>"""

# ============================================================
# MARKDOWN PARSER (minimal, no dependencies)
# ============================================================

def parse_frontmatter(content):
    """Extract YAML-like frontmatter from markdown."""
    meta = {}
    body = content
    if content.startswith('---'):
        parts = content.split('---', 2)
        if len(parts) >= 3:
            for line in parts[1].strip().split('\n'):
                if ':' in line:
                    key, val = line.split(':', 1)
                    meta[key.strip()] = val.strip()
            body = parts[2]
    return meta, body.strip()

def md_to_html(text):
    """Convert basic markdown to HTML."""
    # Code blocks (triple backticks)
    text = re.sub(r'```(\w*)\n(.*?)```', lambda m: f'<pre><code class="language-{m.group(1)}">{m.group(2)}</code></pre>', text, flags=re.DOTALL)
    
    # Inline code
    text = re.sub(r'`([^`]+)`', r'<code>\1</code>', text)
    
    # Headers
    text = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', text, flags=re.MULTILINE)
    text = re.sub(r'^### (.+)$', r'<h3>\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'<h2>\1</h2>', text, flags=re.MULTILINE)
    text = re.sub(r'^# (.+)$', r'<h1>\1</h1>', text, flags=re.MULTILINE)
    
    # Bold and italic
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    
    # Links
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', text)
    
    # Images
    text = re.sub(r'!\[([^\]]*)\]\(([^)]+)\)', r'<img src="\2" alt="\1">', text)
    
    # Blockquotes
    text = re.sub(r'^> (.+)$', r'<blockquote>\1</blockquote>', text, flags=re.MULTILINE)
    
    # Horizontal rules
    text = re.sub(r'^---+$', r'<hr>', text, flags=re.MULTILINE)
    
    # Unordered lists
    text = re.sub(r'^[\-\*] (.+)$', r'<li>\1</li>', text, flags=re.MULTILINE)
    text = re.sub(r'(<li>.*</li>\n?)+', r'<ul>\n\g<0></ul>\n', text)
    
    # Ordered lists
    text = re.sub(r'^\d+\. (.+)$', r'<li>\1</li>', text, flags=re.MULTILINE)
    
    # Tables (basic)
    text = re.sub(r'^\|(.+)\|$', r'<tr><td>\1</td></tr>', text, flags=re.MULTILINE)
    
    # Paragraphs
    paragraphs = text.strip().split('\n\n')
    result = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if re.match(r'^<(h[1-4]|ul|ol|pre|blockquote|hr|table|tr|img)', p):
            result.append(p)
        else:
            result.append(f'<p>{p.replace(chr(10), "<br>")}</p>')
    
    return '\n'.join(result)

# ============================================================
# BUILD FUNCTIONS
# ============================================================

def build_blog(input_dir, output_dir, blog_title="My Blog", blog_description="A simple blog.", 
               author="Anonymous", base_url="/"):
    """Main build function."""
    
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    
    # Clean output
    if output_path.exists():
        shutil.rmtree(output_path)
    output_path.mkdir(parents=True)
    
    # Gather markdown files
    md_files = sorted(input_path.glob('*.md'), key=lambda f: f.stat().st_mtime, reverse=True)
    
    if not md_files:
        print(f"No .md files found in {input_dir}")
        return False
    
    posts = []
    tags = {}
    
    # Process each post
    for md_file in md_files:
        raw = md_file.read_text(encoding='utf-8')
        meta, body = parse_frontmatter(raw)
        
        title = meta.get('title', md_file.stem.replace('-', ' ').title())
        date_str = meta.get('date', datetime.fromtimestamp(md_file.stat().st_mtime).strftime('%Y-%m-%d'))
        description = meta.get('description', body[:150].replace('\n', ' ').strip() + '...')
        post_tags = [t.strip() for t in meta.get('tags', '').split(',') if t.strip()]
        slug = md_file.stem
        
        html_body = md_to_html(body)
        
        post = {
            'title': title,
            'date': date_str,
            'description': description,
            'slug': slug,
            'tags': post_tags,
            'html': html_body,
            'raw_body': body
        }
        posts.append(post)
        
        # Collect tags
        for tag in post_tags:
            if tag not in tags:
                tags[tag] = []
            tags[tag].append(post)
        
        # Build post page
        header = POST_HEADER
        post_html = f"""<article class="post">
<h1>{post['title']}</h1>
<div class="meta">{post['date']} · {len(post['raw_body'].split())} words</div>
<div class="content">
{post['html']}
</div>
<div class="cta">
  <p>Need help processing your data or building a tool like this?</p>
  <a href="mailto:caishen-ai@qq.com" class="btn">Hire me → caishen-ai@qq.com</a>
</div>
</article>"""
        
        page = HTML_TEMPLATE.format(
            title=f"{post['title']} — {blog_title}",
            description=post['description'],
            header=header,
            body=post_html
        )
        
        post_dir = output_path / slug
        post_dir.mkdir(exist_ok=True)
        (post_dir / 'index.html').write_text(page, encoding='utf-8')
        print(f"  OK {slug}/ — '{title}'")
    
    # Build index page
    posts_html = []
    for post in posts:
        posts_html.append(f"""<div class="post">
<h2><a href="/{post['slug']}/">{post['title']}</a></h2>
<div class="meta">{post['date']} · {len(post['raw_body'].split())} words</div>
<p>{post['description']}</p>
</div>""")
    
    index_body = '\n'.join(posts_html)
    index_header = INDEX_HEADER.format(blog_title=blog_title, blog_description=blog_description)
    
    index_page = HTML_TEMPLATE.format(
        title=blog_title,
        description=blog_description,
        header=index_header,
        body=index_body
    )
    
    (output_path / 'index.html').write_text(index_page, encoding='utf-8')
    
    # Build RSS feed
    rss_items = []
    for post in posts[:20]:
        rss_items.append(f"""    <item>
      <title>{post['title']}</title>
      <link>{base_url}{post['slug']}/</link>
      <description><![CDATA[{post['description']}]]></description>
      <pubDate>{post['date']}</pubDate>
    </item>""")
    
    rss = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>{blog_title}</title>
    <link>{base_url}</link>
    <description>{blog_description}</description>
    {''.join(rss_items)}
  </channel>
</rss>"""
    
    (output_path / 'rss.xml').write_text(rss, encoding='utf-8')
    
    # Build sitemap
    sitemap_items = [f'  <url><loc>{base_url}{post["slug"]}/</loc><lastmod>{post["date"]}</lastmod></url>' for post in posts]
    sitemap = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>{base_url}</loc></url>
{chr(10).join(sitemap_items)}
</urlset>"""
    (output_path / 'sitemap.xml').write_text(sitemap, encoding='utf-8')
    
    # Build 404 page
    notfound = HTML_TEMPLATE.format(
        title="404 — Not Found",
        description="Page not found",
        header=POST_HEADER,
        body='<h2>404 — Page Not Found</h2><p>Sorry, that page doesn\'t exist. <a href="/">Go home →</a></p>'
    )
    (output_path / '404.html').write_text(notfound, encoding='utf-8')
    
    print(f"\nStats: {len(posts)} posts, {len(tags)} tags")
    print(f"   RSS: {output_path}/rss.xml")
    print(f"   Sitemap: {output_path}/sitemap.xml")
    print(f"   Output: {output_path}/")
    print(f"   OK: {len(posts)} posts built")
    
    return True

# ============================================================
# CLI
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description='md2blog — Turn Markdown files into a static blog in 1 second.',
        epilog='Example: python md2blog.py ./posts ./output --title "My Blog"'
    )
    parser.add_argument('input', help='Folder containing .md files')
    parser.add_argument('output', help='Output folder for generated HTML')
    parser.add_argument('--title', default='My Blog', help='Blog title')
    parser.add_argument('--description', default='A simple blog.', help='Blog description')
    parser.add_argument('--author', default='Anonymous', help='Author name')
    parser.add_argument('--url', default='/', help='Base URL for RSS/sitemap')
    
    args = parser.parse_args()
    
    print("md2blog -- 1-second static blog generator")
    print(f"   Input:  {args.input}")
    print(f"   Output: {args.output}")
    print()
    
    success = build_blog(
        args.input,
        args.output,
        blog_title=args.title,
        blog_description=args.description,
        author=args.author,
        base_url=args.url
    )
    
    if success:
        print(f"\nDone! Open {args.output}/index.html in your browser.")
    else:
        print("\nBuild failed.")

if __name__ == '__main__':
    main()
